[build]
  command = "npm run build"
  publish = "out"
  ignore_warnings = true

# Handle form submissions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure static assets are served correctly
[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404s - but don't interfere with static assets
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false
